// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gozba_na_klik_backend.Infrastructure.PostgreSql;

#nullable disable

namespace gozba_na_klik_backend.Infrastructure.PostgreSql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520144447_AddRestaurantDetails")]
    partial class AddRestaurantDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MealAllergens", b =>
                {
                    b.Property<int>("AlergenId")
                        .HasColumnType("integer");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.HasKey("AlergenId", "MealId");

                    b.HasIndex("MealId");

                    b.ToTable("MealAllergens");
                });

            modelBuilder.Entity("UserAllergens", b =>
                {
                    b.Property<int>("AlergenId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AlergenId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAllergens");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.Addon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MealId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("TypeOfAddon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("Addons");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gluten"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lactose"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nuts"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shellfish"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Eggs"
                        });
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.CourierWorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CourierWorkingHours");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Description = "10 komada sa lukom",
                            IsDeleted = false,
                            MenuId = 101,
                            Name = "Cevapi",
                            Price = 800m
                        },
                        new
                        {
                            Id = 102,
                            Description = "Gurmanska 250g",
                            IsDeleted = false,
                            MenuId = 101,
                            Name = "Pljeskavica",
                            Price = 700m
                        },
                        new
                        {
                            Id = 103,
                            Description = "Paradajz, krastavac, sir",
                            IsDeleted = false,
                            MenuId = 101,
                            Name = "Sopska Salata",
                            Price = 350m
                        },
                        new
                        {
                            Id = 104,
                            Description = "Domaca corba",
                            IsDeleted = false,
                            MenuId = 101,
                            Name = "Teleca Corba",
                            Price = 400m
                        },
                        new
                        {
                            Id = 105,
                            Description = "Sunka, sir, pecurke",
                            IsDeleted = false,
                            MenuId = 102,
                            Name = "Kapricoza",
                            Price = 900m
                        },
                        new
                        {
                            Id = 106,
                            Description = "Pelat, sir, masline",
                            IsDeleted = false,
                            MenuId = 102,
                            Name = "Margarita",
                            Price = 750m
                        },
                        new
                        {
                            Id = 107,
                            Description = "Kulen, ljuta paprika",
                            IsDeleted = false,
                            MenuId = 102,
                            Name = "Madjarica",
                            Price = 950m
                        },
                        new
                        {
                            Id = 108,
                            Description = "Beli luk, maslinovo ulje",
                            IsDeleted = false,
                            MenuId = 102,
                            Name = "Pica Hleb",
                            Price = 250m
                        },
                        new
                        {
                            Id = 109,
                            Description = "Pohovano meso, kajmak",
                            IsDeleted = false,
                            MenuId = 103,
                            Name = "Karadjordjeva",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 110,
                            Description = "Kupus, suvo meso",
                            IsDeleted = false,
                            MenuId = 103,
                            Name = "Svadbarski Kupus",
                            Price = 850m
                        },
                        new
                        {
                            Id = 111,
                            Description = "Uz tartar sos",
                            IsDeleted = false,
                            MenuId = 103,
                            Name = "Pohovani Kackavalj",
                            Price = 600m
                        },
                        new
                        {
                            Id = 112,
                            Description = "Topla pecena",
                            IsDeleted = false,
                            MenuId = 103,
                            Name = "Domaca Pogaca",
                            Price = 200m
                        },
                        new
                        {
                            Id = 113,
                            Description = "Otkoštani batak 300g",
                            IsDeleted = false,
                            MenuId = 104,
                            Name = "Batak na zaru",
                            Price = 650m
                        },
                        new
                        {
                            Id = 114,
                            Description = "Piletina na zaru",
                            IsDeleted = false,
                            MenuId = 104,
                            Name = "Belo Meso",
                            Price = 600m
                        },
                        new
                        {
                            Id = 115,
                            Description = "Domace kobasice 300g",
                            IsDeleted = false,
                            MenuId = 104,
                            Name = "Kobasice",
                            Price = 750m
                        },
                        new
                        {
                            Id = 116,
                            Description = "Sveze przen",
                            IsDeleted = false,
                            MenuId = 104,
                            Name = "Pomfrit",
                            Price = 250m
                        },
                        new
                        {
                            Id = 117,
                            Description = "Govedji gulas",
                            IsDeleted = false,
                            MenuId = 105,
                            Name = "Gulas",
                            Price = 900m
                        },
                        new
                        {
                            Id = 118,
                            Description = "Kao prilog",
                            IsDeleted = false,
                            MenuId = 105,
                            Name = "Pire Krompir",
                            Price = 200m
                        },
                        new
                        {
                            Id = 119,
                            Description = "U susamu",
                            IsDeleted = false,
                            MenuId = 105,
                            Name = "Pohovana Piletina",
                            Price = 700m
                        },
                        new
                        {
                            Id = 120,
                            Description = "Domaci desert",
                            IsDeleted = false,
                            MenuId = 105,
                            Name = "Krempita",
                            Price = 300m
                        },
                        new
                        {
                            Id = 121,
                            Description = "250g",
                            IsDeleted = false,
                            MenuId = 106,
                            Name = "Burek sa Mesom",
                            Price = 220m
                        },
                        new
                        {
                            Id = 122,
                            Description = "250g",
                            IsDeleted = false,
                            MenuId = 106,
                            Name = "Burek sa Sirom",
                            Price = 200m
                        },
                        new
                        {
                            Id = 123,
                            Description = "Mali kroasan",
                            IsDeleted = false,
                            MenuId = 106,
                            Name = "Kroasan Cokolada",
                            Price = 120m
                        },
                        new
                        {
                            Id = 124,
                            Description = "Casa 0.25l",
                            IsDeleted = false,
                            MenuId = 106,
                            Name = "Jogurt",
                            Price = 60m
                        });
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId")
                        .IsUnique();

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            RestaurantId = 101
                        },
                        new
                        {
                            Id = 102,
                            RestaurantId = 102
                        },
                        new
                        {
                            Id = 103,
                            RestaurantId = 103
                        },
                        new
                        {
                            Id = 104,
                            RestaurantId = 104
                        },
                        new
                        {
                            Id = 105,
                            RestaurantId = 105
                        },
                        new
                        {
                            Id = 106,
                            RestaurantId = 106
                        });
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.NonWorkingDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("NonWorkingDays");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourierId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("Delivery")
                        .HasColumnType("boolean");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("text");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourierId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Address = "Glavna 10, Novi Sad",
                            IsDeleted = false,
                            Name = "Restoran Kod Petra",
                            OwnerId = 101
                        },
                        new
                        {
                            Id = 102,
                            Address = "Dunavska 5, Novi Sad",
                            IsDeleted = false,
                            Name = "Petrova Picerija",
                            OwnerId = 101
                        },
                        new
                        {
                            Id = 103,
                            Address = "Zmaj Jovina 12, Novi Sad",
                            IsDeleted = false,
                            Name = "Markova Kafana",
                            OwnerId = 102
                        },
                        new
                        {
                            Id = 104,
                            Address = "Bulevar Oslobodjenja 45, Novi Sad",
                            IsDeleted = false,
                            Name = "Marko Grill",
                            OwnerId = 102
                        },
                        new
                        {
                            Id = 105,
                            Address = "Laze Teleckog 3, Novi Sad",
                            IsDeleted = false,
                            Name = "Jovanov Restoran",
                            OwnerId = 103
                        },
                        new
                        {
                            Id = 106,
                            Address = "Futoski put 10, Novi Sad",
                            IsDeleted = false,
                            Name = "Pekara Jovan",
                            OwnerId = 103
                        });
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.RestaurantWorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("WorkingHours");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WorkplaceRestaurantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("WorkplaceRestaurantId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin1@gozba_na_klik.com",
                            IsDeleted = false,
                            IsSuspended = false,
                            Name = "Admin1",
                            Password = "admin1",
                            Role = "Admin",
                            Surname = "Admin1",
                            Username = "admin1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "admin2@gozba_na_klik.com",
                            IsDeleted = false,
                            IsSuspended = false,
                            Name = "Admin2",
                            Password = "admin2",
                            Role = "Admin",
                            Surname = "Admin2",
                            Username = "admin2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "admin3@gozba_na_klik.com",
                            IsDeleted = false,
                            IsSuspended = false,
                            Name = "Admin3",
                            Password = "admin3",
                            Role = "Admin",
                            Surname = "Admin3",
                            Username = "admin3"
                        },
                        new
                        {
                            Id = 101,
                            Email = "petar@vlasnik.com",
                            IsDeleted = false,
                            IsSuspended = false,
                            Name = "Petar",
                            Password = "123",
                            Role = "Owner",
                            Surname = "Petrovic",
                            Username = "petar_v"
                        },
                        new
                        {
                            Id = 102,
                            Email = "marko@vlasnik.com",
                            IsDeleted = false,
                            IsSuspended = false,
                            Name = "Marko",
                            Password = "123",
                            Role = "Owner",
                            Surname = "Markovic",
                            Username = "marko_v"
                        },
                        new
                        {
                            Id = 103,
                            Email = "jovan@vlasnik.com",
                            IsDeleted = false,
                            IsSuspended = false,
                            Name = "Jovan",
                            Password = "123",
                            Role = "Owner",
                            Surname = "Jovanovic",
                            Username = "jovan_v"
                        });
                });

            modelBuilder.Entity("MealAllergens", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Domain.Entities.Allergen", null)
                        .WithMany()
                        .HasForeignKey("AlergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gozba_na_klik_backend.Domain.Entities.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserAllergens", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Domain.Entities.Allergen", null)
                        .WithMany()
                        .HasForeignKey("AlergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gozba_na_klik_backend.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.Addon", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Domain.Entities.Meal", null)
                        .WithMany("Addons")
                        .HasForeignKey("MealId");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.Address", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Domain.Entities.User", null)
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.CourierWorkingHours", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Domain.Entities.User", null)
                        .WithMany("CourierWorkingHours")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.Meal", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Domain.Entities.Menu", "Menu")
                        .WithMany("Meals")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.Menu", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Domain.Entities.Restaurant", "Restaurant")
                        .WithOne("Menu")
                        .HasForeignKey("gozba_na_klik_backend.Domain.Entities.Menu", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.NonWorkingDay", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Domain.Entities.Restaurant", null)
                        .WithMany("NonWorkingDays")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.Order", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Domain.Entities.User", "Courier")
                        .WithMany()
                        .HasForeignKey("CourierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gozba_na_klik_backend.Domain.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gozba_na_klik_backend.Domain.Entities.Restaurant", "Restaurant")
                        .WithMany("Orders")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courier");

                    b.Navigation("Customer");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Domain.Entities.Meal", "Meal")
                        .WithMany("OrderItems")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gozba_na_klik_backend.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.Restaurant", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Domain.Entities.User", "Owner")
                        .WithMany("OwnedRestaurants")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.RestaurantWorkingHours", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Domain.Entities.Restaurant", null)
                        .WithMany("WorkingHours")
                        .HasForeignKey("RestaurantId");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.User", b =>
                {
                    b.HasOne("gozba_na_klik_backend.Domain.Entities.Restaurant", "WorkplaceRestaurant")
                        .WithMany("Employees")
                        .HasForeignKey("WorkplaceRestaurantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("WorkplaceRestaurant");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.Meal", b =>
                {
                    b.Navigation("Addons");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.Menu", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.Restaurant", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Menu");

                    b.Navigation("NonWorkingDays");

                    b.Navigation("Orders");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("gozba_na_klik_backend.Domain.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("CourierWorkingHours");

                    b.Navigation("OwnedRestaurants");
                });
#pragma warning restore 612, 618
        }
    }
}
